### ISSUE TITLE
Is there a way to extend the frame that detects the color?

### ISSUE THREAD

**Issue by BorjaJajas** [webosbrew/hyperion-webos#102]
The tv shows everithing in panoramic view and HyperHDR doesn't detect the frame because it is too far. Can I do the detection frame longer?

And another question, is there any option that captures better the colors? I don't mind using more resources.

**Comment by Informatic** [comment]
Yes, this is part of Hyperion-NG and needs to be configured there. Keyword:
"black bar detection"

**Comment by EyalRotem** [comment]
or you can extend the rectangle that calculated the average under (hyperHDR, but should be in Hyperion-NG as well):
![image](https://github.com/webosbrew/hyperion-webos/assets/12516268/e3ad495b-3ed2-4158-9dd6-a943a7aec2c9)
