### ISSUE TITLE
hyperion-webos/PicCap not capturing

### ISSUE THREAD

**Issue by linton85** [webosbrew/hyperion-webos#104]
Rooted with latest HBC, PicCap and HyperHDR
"board_type": "O22_DVB",
"product_id": "OLED42C24LA",
"core_os_release": "7.3.0-20",
"webos_manufacturing_version": "03.30.45",
![image](https://user-images.githubusercontent.com/23485979/223256004-c0f629a7-e337-4afd-9eee-fe535e836a54.png)
![IMG_1218](https://user-images.githubusercontent.com/23485979/223257231-189b7877-c10c-4790-b787-d0d01414e570.jpg)

**Comment by maatthc** [comment]
Same issue here - solved with the following config:
```
{
    "vsync": true,
    "nogui": true,
    "nohdr": true,
    "quirks": 256,
    "fps": 30,
    "priority": 150,
    "height": 180,
    "nopowerstate": false,
    "width": 320,
    "backend": "auto",
    "address": "192.168.100.99",
    "port": 19400,
    "unix-socket": false,
    "autostart": true,
    "uibackend": "auto",
    "novideo": false
}
```

My tv has a similar Os version: 
```
   "board_type": "LM21A_DVB",
    "hardware_id": "HE_DTV_W22A_AFADATAA",
    "product_id": "75UQ9000PSD",
    "core_os_release": "7.3.0-2407",
    "webos_manufacturing_version": "03.30.72",
```

**Comment by TBSniller** [comment]
@linton85: You should try to higher the resolution. As far as I've seen most of the libvtcapture TVs should use 320x - lower resolutions are only working for some video formats, but not all.

Furthermore capture will only start if a non drm protected video is playing. For the meantime it's possible, that you are receiving such kind of error. Capture init will be tried until a video is playing:
https://github.com/webosbrew/hyperion-webos/blob/10b638fffcb2dde62060f9cd64aad2d406278e73/src/backends/libvtcapture.cpp#L264-L267
