### ISSUE TITLE
Glitches on top of screen when capturing from HDMI inputs

### ISSUE THREAD

**Issue by avocadobeachy** [webosbrew/hyperion-webos#111]
I have an LG 49SM8600PLA rooted and running PiCap (calling hyperion-webos) with Hyperion-NG. The capturing works fine with Live TV and smart TV apps such as Netflix, but when capturing from any HDMI sources there are glitches on the top of the screen (videos showing this attached), that show anytime the capturing is running. I have also attached what the capturing looks like when from an HDMI source.

These also occur on the 'No Input Detected' screen. Stopping the hyperion-webos service stops these glitches, but as soon as you start it again they show up. I have tried various quirks but none of these seem to resolve this issue. Any ideas what I can try?

https://github.com/webosbrew/hyperion-webos/assets/35968760/d889f352-42ee-42be-8d94-da3970ca2c55

https://github.com/webosbrew/hyperion-webos/assets/35968760/2f2fceae-1eb1-4a6d-995a-042ad47b9115

https://github.com/webosbrew/hyperion-webos/assets/35968760/a9911e47-c1c4-426d-b206-04e73a525cfa

**Comment by Logarythms** [comment]
I had the same issue tonight on my LG B9 Oled, and enabling QUIRK_DILE_VT_CREATE_EX under advanced settings seems to have fixed it for me

**Comment by avocadobeachy** [comment]
@Logarythms thanks for this, seems to have sorted it for me now as well!
