### ISSUE TITLE
Scaleup/down limitations

### ISSUE THREAD

**Issue by dieseld23** [webosbrew/hyperion-webos#15]
Doesn't seem the limitations reported from dile_vt are the actual scale down limits. Once I run, i have no problem running at 192x108 (when tv reports scale down is 320x240, which is also weird cause that's not a widescreen resolution)

**Comment by Informatic** [comment]
You mean - that resolution works for you when you comment out/remove these overwrites?
https://github.com/webosbrew/hyperion-webos/blob/dile_vt_getallvfb/src/backends/libdile_vt.c#L112-L113

**Comment by dieseld23** [comment]
yeah, i can scale down below that without any issue when i comment out those overwrites

    "board_type": "O18_ATSC",
    "hardware_id": "HE_DTV_W19O_AFABATAA",
    "product_id": "OLED65C9PUA",
    "core_os_release": "4.9.1-53409",
    "webos_manufacturing_version": "05.00.30",
