### ISSUE TITLE
Failed to load backend library: libvtcapture_backend.so

### ISSUE THREAD

**Issue by tavalin** [webosbrew/hyperion-webos#18]
Hi @Informatic  seems with the recent commits, I can no longer use `libvtcapture` as the backend.  The `hyperion-webos_libvtcapture` that ships in PicCap still works though.

```
root@LGwebOSTV:/tmp# LD_LIBRARY_PATH=. ./hyperion-webos -a 192.168.0.191 -b libvtcapture
Error! Failed to load backend library: libvtcapture_backend.so, error: libhalgal.so.1: cannot open shared object file: No such file or directory
Error! detect_backend.
root@LGwebOSTV:/tmp# ldconfig -p | grep libhalgal
        libhalgal.so.2 (libc6) => /usr/lib/libhalgal.so.2
        libhalgal.so (libc6) => /usr/lib/libhalgal.so
root@LGwebOSTV:/tmp# grep -h -E '"(hardware_id|core_os_release|product_id|webos_manufacturing_version|board_type)"' /var/run/nyx/*
    "board_type": "O20_DVB",
    "hardware_id": "HE_DTV_W21O_AFABATAA",
    "product_id": "OLED55G16LA",
    "core_os_release": "6.0.1-454907",
    "webos_manufacturing_version": "03.11.23",
```

**Comment by Informatic** [comment]
Ah, I suspect we may be missing some modifications (abi version specificiation) in tv-native-services.
@TBSniller can you please take a look at it?

**Comment by Informatic** [comment]
https://github.com/TBSniller/tv-native-apis/commit/6e6d3d326ef15d3c9ef93c26206612fa6bfb009d Yeah - that's the specific commit that needs to be updated in upstream tv-native-apis side.

**Comment by Informatic** [comment]
Can you please check version in #19 if it works properly?

**Comment by tavalin** [comment]
> Can you please check version in #19 if it works properly?

Managed to get a bit further:

```
root@LGwebOSTV:/tmp# LD_LIBRARY_PATH=. ./hyperion-webos -b libvtcapture -a 192.168.0.191
Init graphical capture..
HAL_GAL_Init done! Exit: 0
HAL_GAL_CreateSurface done! SurfaceID: 250
HAL_GAL_CaptureFrameBuffer done! 0
HAL_GAL: gfx open ok result: 14
Halgal done!
Init video capture..
terminate called after throwing an instance of 'std::runtime_error'
  what():  LSRegisterPubPriv FAILED
[1]+  Stopped (signal)           ./hyperion-webos -b libvtcapture -a 192.168.0.191
```

**Comment by Informatic** [comment]
Great. That error is expected, since `/tmp/hyperion-webos` does not have its luna bus permissions set up properly. This is the part where `task/native-service` branch that @TBSniller works on comes in. Not sure what is the current state of that.

**Comment by tavalin** [comment]
Is there a workaround to get the permissions working temporarily? Or am I unable to test any further for now?

**Comment by TBSniller** [comment]
@tavalin, as already wrote in discord:

you can use this script (edit cp to your needed paths):
https://github.com/TBSniller/piccap/blob/main/service/piccap.service/setlibvtcaptureperms.sh
cp -f /path/to/manifest.json /usr/share/luna-service2/manifests.d/screen-capture-webos.manifest.json
cp -f /path/to/role.json /usr/share/luna-service2/roles.d/org.webosbrew.piccap.service.role.json

you will need these files - copy them to a location you edited above
https://github.com/TBSniller/piccap/blob/main/service/piccap.service/screen-capture-webos.manifest.json
https://github.com/TBSniller/piccap/blob/main/service/piccap.service/org.webosbrew.piccap.service.role.json (in this file you have to edit exeName parameter, to the path you need (/tmp/hyperion/hyperion-webos))

**Comment by tavalin** [comment]
Hey @TBSniller any ideas on this? I still can't get the master branch to run properly using the libvtcapture backend due to permission issues.

**Comment by TBSniller** [comment]
Yeah, you can check again with releasing the new version: https://github.com/TBSniller/piccap/pull/18 
For the meantime and if you are knowledged enough you can check this pre release: https://github.com/TBSniller/piccap/releases/tag/0.2.2

**Comment by tavalin** [comment]
Installing version 0.2.2 works ok for me
