### ISSUE TITLE
GLES Renderer to generate image frame

### ISSUE THREAD

**Issue by mariotaku** [webosbrew/hyperion-webos#2]
Now we can get image frame of video and compositor (UI) separately. And we need to combine them into one image.

### Video Layer

Texture [`_vt_texture_id`](https://github.com/webosbrew/hyperion-webos/blob/main/src/renderer.c#L23), RGBA format, vertically flipped

### Compositor Layer

Uint8 array [`_gm_framebuffer`](https://github.com/webosbrew/hyperion-webos/blob/bba2f28e52aaecf5ecbf79e9b4434636b37360de/src/renderer.c#L22), BGRA format

## Process

Flip video layer vertically to the right direction, and put compositor layer on top of it with B and R channel swapped.

## Render

Render 2 layers above into framebuffer in [`renderer_generate`](https://github.com/webosbrew/hyperion-webos/blob/bba2f28e52aaecf5ecbf79e9b4434636b37360de/src/renderer.c#L228)

**Comment by tuxuser** [comment]
Solved via `unicapture` branch.
