### ISSUE TITLE
Code formatting/linting

### ISSUE THREAD

**Issue by Informatic** [webosbrew/hyperion-webos#26]
Our codestyle is all over the place. It would be nice to suggest some sensible code formatter/linter for this project.

I heard some good words about `clang-tidy`. Only issue I can see is that it depends on whole clang enironment, and may need some configuration adjustments to work with our NDK properly. I will look into this soon.

**Comment by Informatic** [comment]
OK, the part that is mostly interesting for us initially is `clang-format` (formatter, tidy is a linter/checker), the only question is what codestyle do we go with. Google seems sensible.

**Comment by tuxuser** [comment]
Unicapture has the .clang-format defined (https://github.com/webosbrew/hyperion-webos/blob/unicapture/.clang-format)

Should we enforce it via CI to solve this issue?

**Comment by tuxuser** [comment]
Could utilize this script:
https://github.com/Sarcasm/run-clang-format

**Comment by TBSniller** [comment]
Done with https://github.com/webosbrew/hyperion-webos/pull/85
