### ISSUE TITLE
Can this run on TV?

### ISSUE THREAD

**Issue by grosseskino** [webosbrew/hyperion-webos#3]
Hi!
I just found this as I am looking for a hyperion integration for my TV.

Is it possible to run this on my LG TV?
How can I install it - will you release an .ipk ?

Thanks in advance!

**Comment by mariotaku** [comment]
Hello, this is still in very early stage as an experiment. But indeed works. And some people is still working on making it usable. Please keep an eye on it!

**Comment by YoBnEb** [comment]
Hi,

thanks for your efforts here!
Will "root" access be necessary for using this implementation?

I think I have to setup an webos build environment :-)

**Comment by mariotaku** [comment]
> Hi,
> 
> thanks for your efforts here!
> Will "root" access be necessary for using this implementation?
> 
> I think I have to setup an webos build environment :-)

I believe root is not needed. And nothing is needed except a working ssh client. So stay tuned :)

**Comment by mariotaku** [comment]
> Hi,
> 
> thanks for your efforts here!
> Will "root" access be necessary for using this implementation?
> 
> I think I have to setup an webos build environment :-)

Sorry, last reply was referred to another issue. Some user have reported that root is required on webOS 5+. And on webOS 3 nobody has succeeded yet.

**Comment by lsaadeh** [comment]
How do you go about installing this?

**Comment by lifeandfate1** [comment]
Yea I would love to install this, are there any instruction as to what to do? I'm not familiar with sideloading onto an LG webOS TV

**Comment by Informatic** [comment]
User-friendly distribution see https://github.com/TBSniller/piccap
