### ISSUE TITLE
Realistic chance of release in near future?

### ISSUE THREAD

**Issue by snipah** [webosbrew/hyperion-webos#4]
First of all, thanks for your great work. Some questions:
1. How is the current functionality? What is working, what is not?
2. Do we have a realistic chance to see a release soon?
3. Is this based on Hyperion.ng?
4. Which protocols are currently supported? Can I use WLED?

Thanks and best regards,
Andre

**Comment by mariotaku** [comment]
Unfortunately this is still highly experimental and not in active development.

* It uses private API in webOS system, and it changes often across versions, causes it only working in certain TV
* In most cases rooting your TV is required
* Event it works, it will break something like "No signal" screen or even HDMI input, causes wild flickering until reboot

So there's still no realistic estimation to its release date. If everything work though, it is a network service of Hyperion, which is to send data to your main Hyperion.ng server to make it glow.

**Comment by AkdM** [comment]
Even if it's still in its early development, is hyperion-webos receiving the image data through HDMI or it *scans* the screen thanks to the app directly?

**Comment by mariotaku** [comment]
@AkdM Actually it is intended to forward all contents on screen - esp. video feed including but not limited to HDMI.

**Comment by AkdM** [comment]
@mariotaku So it will forward all contents on screen through the network, or will it also be able to transfer the infos to the USB port of the TV?

**Comment by mariotaku** [comment]
> @mariotaku So it will forward all contents on screen through the network, or will it also be able to transfer the infos to the USB port of the TV?

It will forward (down-scaled) screen content through the network.

**Comment by AkdM** [comment]
Fine. As it's not a webos app, and root is apparently mandatory for executing it, there should be a little guide on how to execute it / debug.
I am not familiar to webos development (yet), and I'm interested on helping on this project. But I want to know what's on your mind and what path you planned to take before dedicating time to it 👍

**Comment by TBSniller** [comment]
We now create releases.
For ready to install IPK release see https://github.com/TBSniller/piccap/releases
For standalone files see https://github.com/webosbrew/hyperion-webos/releases
