### ISSUE TITLE
Image syncronization problem

### ISSUE THREAD

**Issue by TurburatoR** [webosbrew/hyperion-webos#46]
[log_message.txt](https://github.com/webosbrew/hyperion-webos/files/7985453/log_message.txt)
![screen](https://user-images.githubusercontent.com/98270876/152134609-525ea871-f5d0-42f9-a9d0-834836874e5b.jpg)

    "board_type": "K3LP_DVB",
    "hardware_id": "HE_DTV_W17P_AFADABAA",
    "product_id": "55UJ630V-ZA",
    "core_os_release": "3.9.0-62906",
    "webos_manufacturing_version": "06.00.20",

**Comment by TurburatoR** [comment]
everything worked at a resolution of 320х240. thnx.

**Comment by TBSniller** [comment]
@TurburatoR Which settings and backed are you using?

**Comment by Zerberuss** [comment]
Probably same Issue with C9
https://user-images.githubusercontent.com/15108282/154104359-acccd4ee-85f3-463a-8699-4262372308bc.mp4

Tested 320x240 with 60 and 15fps
Always same result.

**Comment by Zerberuss** [comment]
Update:
Fixed by using the old capture mode AND using an usb-ethernet adapter instead of wifi
