### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by RestOp** [webosbrew/hyperion-webos#49]
Hello,

    "board_type": "K3LP_DVB",
    "hardware_id": "HE_DTV_W17P_AFADABAA",
    "product_id": "49UJ630V-ZA",
    "core_os_release": "3.9.0-62906",
    "webos_manufacturing_version": "06.00.20",

i am a newbie
I have downloaded code from this page 
https://github.com/webosbrew/hyperion-webos/actions/runs/1568099580
Copied all files to tmp/hyperion-webos
![image](https://user-images.githubusercontent.com/46259141/153494073-9277a087-497c-4fdf-bcf9-38115e106249.png)

But when i try to start it with this
![image](https://user-images.githubusercontent.com/46259141/153494135-001b9902-9e57-446b-83e8-3687141fc2f1.png)

i get 
![image](https://user-images.githubusercontent.com/46259141/153494162-53a1709f-2da6-4e5b-8d63-732c28726acc.png)

Could you please help me!
Thanks!

**Comment by Informatic** [comment]
you need to run `chmod +x ./hyperion-webos`

Also - is there some specific reason to try such an old version? Current Homebrew Channel version should work equally well.

**Comment by RestOp** [comment]
Thanks a lot!
I just found these files, i am new to github and do not know how it works here...
Could you explain how to get an Homebrew Channel version or you mean piccap (UI of piccap do not work for me)?

**Comment by RestOp** [comment]
By the way i tried to chmod but
![image](https://user-images.githubusercontent.com/46259141/153496771-12c1fab1-78e3-46f0-a54f-32f966e00ca1.png)

**Comment by Informatic** [comment]
try adding `-x 192 -y 108` options to that line to limit resolution

**Comment by RestOp** [comment]
Now Perfect!!! Thanks a lot! Works great!

![image](https://user-images.githubusercontent.com/46259141/153499265-906978dc-5876-450e-846a-b47f80c03b7f.png)

Not i need to find out how to start thsi command with the start of TV... Is there any solution?

**Comment by Informatic** [comment]
Yeah - the proper solution would be to figure out why is the UI/background service not working. Which Homebrew Channel version do you have installed? PicCap depends on some script changes introduced in v0.4.0.

**Comment by RestOp** [comment]
I have just made a https://rootmy.tv/ 
So actually i have version 0.4.0 and PicCap 0.23
But it is not only my problem with UI as i can see. And it is now fixed till now. So i am looking for way to start the program without PicCap. Actually i have not need in UI, if i alredy defined all settings...

**Comment by RestOp** [comment]
Thanks one more time!!!
It worked for me!
![image](https://user-images.githubusercontent.com/46259141/153502512-996c1eea-5dfd-41b7-9ad8-78ac2513961d.png)

And after reboot of TV hyperion-webos is UP!!!

Great! The issure can be closed!
Thanks!!!
