### ISSUE TITLE
Errors on LG TV

### ISSUE THREAD

**Issue by zlokomatic** [webosbrew/hyperion-webos#5]
My lg tv is rooted and i got the source to compile using the ndk.
But when running i get an egl error:
```[EGL] Display, major = 1, minor = 4
hyperion-webos: /source/src/capture.c:206: egl_init: Assertion `eglGetError() == EGL_SUCCESS' failed.
```

Also when im skipping the egl part i get the error:

```
[VT] VT_IsSystemSupported Failed. This TV doesn't support VT.
```

Maybe you can give me a hint how to debug this and maybe what other api i could try to capture the screen?

**Comment by Informatic** [comment]
Not sure if you are following it, but we started reversing `libdile_vt` which is an underlying library used by `libvt`, and we've been able to make it work on at least one model where `libvt` was broken.

You can try if that works. Prebuilt binaries are here: https://github.com/webosbrew/hyperion-webos/actions/runs/1569221042

```sh
LD_LIBRARY_PATH=/tmp /tmp/hyperion-webos --address 10.0.0.1 --port 19400 --fps 60 --width 192 --height 108 --backend libdile_vt
```

We only support RGB pixel format (`pixelFormat: 9`) right now, but I soon will add pixel format conversions

**Comment by zlokomatic** [comment]
Hi,

thank you its working now on my tv with constant 6 fps. :)

I got the output:

```[DILE_VT] pixelFormat: 9; width: 576; height: 108; stride: 576...```

but i used a width of 192. Is this just a display error or is the resolution really wrong?

**Comment by zlokomatic** [comment]
Thats the output i got:

```
[DILE_VT] supportScaleUp: 0; (0x0)
[DILE_VT] supportScaleDown: 1; (60x34)
[DILE_VT] maxResolution: 1920x1080
[DILE_VT] input deinterlace: 0; display deinterlace: 0
[DILE_VT] framerate divider: 1
[DILE_VT] vfbs: 1; planes: 1
[DILE_VT] pixelFormat: 9; width: 576; height: 108; stride: 576...
[DILE_VT] vfb[0][0] = 0x08000000
Start connection loop
[DILE_VT] framerate: 0.015127 FPS
[DILE_VT] vfb 0: pixelFormat: 9; width: 576; height: 108; stride: 576; offset: 08000000... ok!
[DILE_VT] framerate: 6.034332 FPS
[DILE_VT] framerate: 6.014026 FPS
[DILE_VT] framerate: 6.014061 FPS
[DILE_VT] framerate: 6.034264 FPS
[DILE_VT] framerate: 6.013991 FPS
[DILE_VT] framerate: 6.014071 FPS
```
6 fps is already better than the 2 fps i got with triggering luna://com.webos.service.tv.capture/executeOneShot :D

TV Model: LG 55UH625V
webOS Version: 3.4.0-5803
Software Version: 05.60.03

**Comment by Informatic** [comment]
If you are up for some hacking you could try commenting out or replacing this line with some generic sleep like `usleep(30000);`
https://github.com/webosbrew/hyperion-webos/blob/main/src/backends/libdile_vt.c#L181

**Comment by zlokomatic** [comment]
[DILE_VT] framerate: 26.837904 FPS 🎉

**Comment by Informatic** [comment]
And does it *actually* feed proper frames? That's amazing, we could rework our code to do that (optionally)

**Comment by zlokomatic** [comment]
I think so. I only checked it in the hyperion web live view and it looked really good. I could not see any skipped/black frames
so i assume it is working

**Comment by Informatic** [comment]
Great. I'll try to add detection of misbehaving `WaitVsync` and will likely need your help sometime later. :)

**Comment by zlokomatic** [comment]
Sure, just tell me when to test :)

**Comment by derstrassi** [comment]
I've been fiddling around with one of the latest builds (https://github.com/webosbrew/hyperion-webos/actions/runs/1569221042).
SDR and HDR content is working pretty good except Dolby Vision. If the TV plays Dolby Vision content the screen goes black or pink when using `libvt` backend, `libdile_vt` produces a distorted b/w image in Hyperion Live-Video. Framerate is great.

Is there any debug log I can contribute?

Model: LG 65B7D
webOS: 3.9.0
Software: 06.00.25

**Comment by Informatic** [comment]
@derstrassi can you please check build from a previous commit (https://github.com/webosbrew/hyperion-webos/actions/runs/1569884562), share with us `/tmp/hyperion-webos-dump.000.000.raw` and `/tmp/hyperion-webos-dump.000.001.raw` files that are genrated, and log of a run of `hyperion-webos`?

**Comment by Informatic** [comment]
@zlokomatic can you check #12 once again? We added some startup call that was seemingly missing. We also added an initial vsync timing test, but do not detect misbehaviour yet:

```
[DILE_VT] frametime: 16120; estimated fps before divider: 62.03474
[DILE_VT] frametime: 33121; estimated fps after divider: 30.19233
```

**Comment by derstrassi** [comment]
@Informatic tried this build, but none of the files you mentioned was generated. Do I have to send a specific kill signal?

**Comment by Informatic** [comment]
Can you show us the log you got? It should have printed out these messages: https://github.com/webosbrew/hyperion-webos/commit/887ccd967c7929afc9a12e1b17d66cb44c360904#diff-c66171c49549a5d2b7a37f4536054a651e8a049a6ed0f71efcf981f29dcbfcb7R204-R212

**Comment by derstrassi** [comment]
But wait...now I have tried the latest build (https://github.com/webosbrew/hyperion-webos/actions/runs/1598688764) and used `libdile_vt` backend and it works perfectly with my B7 TV and DV content!
Thought I have to use `libvt` as backend because `libdile_vt` never gave me a clear picture in Hyperion preview.

Log output is:
```
root@LGwebOSTV:~/tmp# LD_LIBRARY_PATH=/home/root/tmp /home/root/tmp/hyperion-webos --address 192.168.10.5 --port 19400 --backend libdile_vt

[DILE_VT] supportScaleUp: 1; (3840x2160)
[DILE_VT] supportScaleDown: 1; (320x240)
[DILE_VT] maxResolution: 3840x2160
[DILE_VT] input deinterlace: 0; display deinterlace: 1
[DILE_VT] scaledown limit, overriding to 320x240
[DILE_VT] framerate divider: 1
[DILE_VT] frametime: 16676; estimated fps before divider: 59.96642
[DILE_VT] frametime: 16683; estimated fps after divider: 59.94126
[DILE_VT] vfbs: 3; planes: 2
[DILE_VT] pixelFormat: 1; width: 320; height: 240; stride: 320...
[DILE_VT] vfb[0][0] = 0xbcd00000
[DILE_VT] vfb[0][1] = 0xbcd13000
[DILE_VT] vfb[1][0] = 0xbcd1d000
[DILE_VT] vfb[1][1] = 0xbcd30000
[DILE_VT] vfb[2][0] = 0xbcd3a000
[DILE_VT] vfb[2][1] = 0xbcd4d000
Start connection loop
[DILE_VT] framerate: 0.538473 FPS
[DILE_VT] framerate: 30.482291 FPS
[DILE_VT] framerate: 29.973234 FPS
```

**Comment by Informatic** [comment]
Well that's great then I guess. Seems like we are limited to 30fps performance-wise though? If you want to debug it yourself some more, you can try commenting out scaledown limiter like in #15  and see if you can go down to something like 192x108. Also *I persume* the performance/latency would be slightly better if you set `-f 30` (since we wouldn't even try decoding/pulling in every second frame, that we aren't able to convert quickly enough as seen above in framerate counter)

**Comment by derstrassi** [comment]
Will trie that with the scale down, but I don't know if that is necessary. Did set `--fps 15` and performance seems good to me, around 12% CPU for hyperion-webos and no latency noticeable.

**Comment by Informatic** [comment]
Sure, depends on what's your target. I feel like 15 → 30 would be definitely noticeable improvement.

**Comment by Informatic** [comment]
Closing since this has been mostly resolved, if I understand it correctly. Don't hestitate to reopen/create new issues.

**Comment by v-Bauer** [comment]
I have the same TV as @zlokomatic (but 65") with the same OS Version and got exactly the same error with only 6 FPS.

Replacing DILE_VT_WaitVsync(vth, 0, 0); with usleep(30000); helped. Now I'm at 30 FPS.

    "board_type": "K2LP_DVB",
    "hardware_id": "HE_DTV_W16P_AFADABAA",
    "product_id": "65UH625V-ZA",
    "core_os_release": "3.4.0-5803",
    "webos_manufacturing_version": "05.60.03",
