### ISSUE TITLE
is it right that with PicCap + hyperion-webos HDR content recognition (over HDMI in) is working correctly?

### ISSUE THREAD

**Issue by menotuu** [webosbrew/hyperion-webos#52]
With PicCap + hyperion-webos there will be no more problems with the recognition of HDR content, right? 
or is there a hyperhdr-webos in development?

**Comment by tuxuser** [comment]
This will be worked on at some point. Currently, inofficial builds exist that implement this switch via inline `curl` calls to hyperhdr.

https://github.com/webosbrew/hyperion-webos/actions/runs/2352883844

This indeed requires HyperHDR as the ambient lighting daemon

**Comment by TBSniller** [comment]
Implemented in latest releases
