### ISSUE TITLE
Error - malloc(): unsorted double linked list corrupted

### ISSUE THREAD

**Issue by begemotik** [webosbrew/hyperion-webos#58]
Platform: LG WebOS 6.2.0-35

When running PicCap with Hyperion, Hyperion becomes unresponsive shortly after launcing PicCap. Log shows:
```
Mar 19 13:44:55 raspberrypi hyperiond[1737]: malloc(): unsorted double linked list corrupted
Mar 19 13:44:55 raspberrypi hyperiond[1737]: Hyperion caught signal :SIGABRT
```

Would appreciate your insight on the problem.

**Comment by Informatic** [comment]
Kill `hyperion-webos` process on the TV, and download and replace files in `/media/developer/apps/usr/palm/services/org.webosbrew.piccap.service` with ones from that CI build: https://github.com/webosbrew/hyperion-webos/actions/runs/1765916878 (https://github.com/webosbrew/hyperion-webos/pull/40)

**Comment by begemotik** [comment]
Hyperion doesn't hang with this build used, thought I still can't manage the LED to work. I should note that the hardware setup is surely working as I've tested it with [Windows grabber](https://sabaatworld.github.io/HyperionScreenCap/). 

Log ouput of Hyperion now:
```
Mar 19 15:02:09 raspberrypi H[2020]: ImageProcessor::process called with image size 0
Mar 19 15:02:11 raspberrypi hyperiond[2020]: 2022-03-19T15:02:11.720  IMAGETOLED            : <WARNING> Previous line repeats 200 times
```

Thanks for your work, @Informatic! Much appreciated.

**Comment by begemotik** [comment]
Also I can confirm that I see the persistent tcp connection from my tv to `hyperion-instance:19400`.

**Comment by Informatic** [comment]
Have you checked if "Preview" window in hyperion shows anything? Does the UI layer (home screen, settings app and such...) show up there? Have you tried rebooting the TV? (Homebrew Channel → Settings → Reboot)

**Comment by begemotik** [comment]
Yes, I've tried rebooting hyperion and TV, seems to make no effect. In the "Preview" windows it's constantly showing nothing regardless what app launched. Worth noting that when I choose "Effects Configurator" and hit "Start test" I see that the LED works and I see in the preview that diods are sparkling.

Any other log file or config set I can share to provide more info?

**Comment by begemotik** [comment]
Other observed stranges - if I change the Width and Height and relaunch PicCap, connection from remote to TV instantly becomes unstable, at the Preview window I see black screen instead of `Hypereion` logo. Also tried "Graphic capture" and it works in the Preview window, though when I launch any video I see black screen in the Preview, remote is also unstable.

**Comment by tuxuser** [comment]
- Which backends did you try so far (libdile_vt, libvt, libvtcapture) ? libdile_vt is preferred
- Which resolutions and fps were tried? (try something like 192x108, fps: 30)
- Which capture sources are you testing (youtube, hdmi, live tv?) - netflix and amazon or any app playing copyrighted material wont work

**Comment by begemotik** [comment]
It seems that it's finally working, the configuration used: 192x108, 20fps(if set 30 remote control is sligtly slow), libvtcapture. Tried other backends and it wasn't successful (libdile_vt - black screen, libvt - it didn't start). Thanks @Informatic, @tuxuser.

@Informatic, are there any plans to release the changes - https://github.com/webosbrew/hyperion-webos/actions/runs/1765916878 (https://github.com/webosbrew/hyperion-webos/pull/40)? Would be nice to have it working out of the box with PicCap.

**Comment by Informatic** [comment]
Yeah, these fixes are integrated in #43, which will probably be our way forward in the next release.

If you you are noticing slowness with 192x108@30 your TV is probably running on 2.4GHz Wi-Fi (same radio is shared between wifi and BLE for remote control communication) - either try 5GHz or switch to ethernet.

**Comment by begemotik** [comment]
Yes, indeed, with 5GHz works without slowness. 
The last question, it's not related to the original problem though. When I turn on TV after sleep and launch video I expect TV to start streaming the video captured to Hyperion, but it doesn't happen until PicCap stopped and started again. Is there a chanse that I missed some setup option? `Autostart` feature is enabled.

**Comment by begemotik** [comment]
> Yes, indeed, with 5GHz works without slowness.
> 
> The last question, it's not related to the original problem though. When I turn on TV after sleep and launch video I expect TV to start streaming the video captured to Hyperion instantly, but it doesn't happen until PicCap stopped and started again. Is there a chance that I missed some setup option? `Autostart` feature is enabled.

For future refference - https://github.com/TBSniller/piccap#not-working

**Comment by Informatic** [comment]
FYI resume after sleep with QuickStart+ *enabled* should work fine on #43 (but that is not fully compatible with current PicCap GUI yet)
