### ISSUE TITLE
Question about added video output latency

### ISSUE THREAD

**Issue by microraptor** [webosbrew/hyperion-webos#62]
Does running the capture add extra latency between video source and output on the TV or is it highly unlikely from from a technical standpoint? Perhaps the executable might have a high CPU load or occupy much memory on older models. Is there a way to test this?

This is important for some gaming, where a few ms make a difference and perhaps stopping the Webos capture and for example using a Hyperion capture on the gaming PC might be a much better option.

**Comment by Informatic** [comment]
We are not aware of that.

Generally (highly oversimplified) video coming from inputs onto the display basically bypass the CPU/GPU.
Video capture only "reads out" buffer that are already displayed on the display. UI capture extracts rendered frames from the GPU (GPU is only responsible for rendering of non-video parts on the screen). The only effect hyperion-webos has on a TV is increased network usage and CPU usage - which can cause UI to "slow down" a little, but *not* affect video playback.

**Comment by microraptor** [comment]
Thank you for taking the time to answer this question and for working on this awesome project!
