### ISSUE TITLE
Can't start any backend with various error

### ISSUE THREAD

**Issue by DrPollio** [webosbrew/hyperion-webos#67]
Hi Everyone,

First I'd like to say thanks for the team working on this solution the grabber is the only weak point on the Hyperion system and it's Wonderfull to be able to use his TV to do de work :). 

But I can't get  any backend to work, No problem to root the TV and install piccap (even if the iterface doesn't work) same for home-brew (I don't know why but it says it's not elevated). 
Even so when I work using ssh I can't make the backend work. 

For information this is my system: 

>"board_type": "M16_DVB",
>"hardware_id": "HE_DTV_W16N_AFADABAA",
>"product_id": "49UH650V-ZB",
>"core_os_release": "3.4.0-5908",
>"webos_manufacturing_version": "05.60.25",

So using Libcapture with this config I get:

>root@LGwebOSTV:/# /media/developer/apps/usr/palm/services/org.webosbrew.piccap.service/hyperion-webos -a 192.168.1.11 --verbos
     0.000s [INFO main                ] Starting up...
     0.001s [ DBG parse_options       ] Finished parsing arguments
     0.004s [ DBG main                ] Checking service root status...
     0.005s [ DBG check_root          ] Service is running as root!
     0.005s [ DBG main                ] Setting default settings before loading...
     0.005s [ DBG set_default         ] Setting default settings to runtime...
     0.005s [ DBG set_default         ] Finished setting default.
     0.005s [ DBG main                ] Loading settings from disk to runtime...
     0.005s [ DBG load_settings       ] Try to read configfile.
     0.005s [ DBG load_settings       ] Read configfile at /media/developer/apps/usr/palm/services/org.webosbrew.piccap.service/config.json. Contents: {"backend":"libdile_vt","address":"192.168.1.11","port":19400,"width":480,"height":270,"fps":0,"autostart":true,"nogui":false,"novideo":false}
     0.005s [ DBG load_settings       ] Loaded these values: Address: 192.168.1.11 | Port: 19400 | Width: 480 | Height: 270 | FPS: 0 | Backend: libdile_vt | NoVideo: 0 | NoGUI: 0 | Autostart: 1
     0.005s [ DBG capture_main        ] Using these values: Address: 192.168.1.11 | Port: 19400 | Width: 480 | Height: 270 | FPS: 0 | Backend: libdile_vt | NoVideo: 0 | NoGUI: 0 | Autostart: 1
     0.005s [ DBG capture_main        ] Detecting backend...
     0.005s [ DBG import_backend_library] Full library path: /media/developer/apps/usr/palm/services/org.webosbrew.piccap.service/libdile_vt_backend.so
     0.010s [ DBG capture_main        ] Backend preinit...
     0.010s [INFO capture_preinit     ] Preinit called. Copying config..
     0.010s [ DBG capture_main        ] Initiating capture...
     0.010s [INFO capture_init        ] Init called
     0.010s [ DBG capture_main        ] Starting capture..
     0.011s [INFO capture_start       ] Capture start called.
KADP_DE_SetDHDRInit : Done. 
     0.033s [ DBG capture_start       ] Got DILE_VT context!
     0.033s [ DBG capture_start       ] supportScaleUp: 1; (1920x1080)
     0.033s [ DBG capture_start       ] supportScaleDown: 1; (320x240)
     0.033s [ DBG capture_start       ] maxResolution: 1920x1080
     0.033s [ DBG capture_start       ] input deinterlace: 0; display deinterlace: 1
     0.034s [ ERR capture_main        ] Error! capture_start. Code: -2
     0.034s [ DBG cleanup             ] Starting cleanup... isRunning: 0
     0.034s [ DBG cleanup             ] Destroying hyperion-client...
     0.034s [ DBG cleanup             ] Cleanup capture within library...
     0.035s [ DBG cleanup             ] Cleanup finished.
     0.035s [ ERR main                ] Capture main init failed!
     0.035s [ DBG main                ] Going into main loop..

when I try with libvtcapture I get:

>root@LGwebOSTV:/# /media/developer/apps/usr/palm/services/org.webosbrew.piccap.service/hyperion-webos -a 192.168.1.11 -verbos
     0.000s [INFO main                ] Starting up...
     0.001s [ DBG parse_options       ] Finished parsing arguments
     0.004s [ DBG main                ] Checking service root status...
     0.004s [ DBG check_root          ] Service is running as root!
     0.004s [ DBG main                ] Setting default settings before loading...
     0.004s [ DBG set_default         ] Setting default settings to runtime...
     0.004s [ DBG set_default         ] Finished setting default.
     0.004s [ DBG main                ] Loading settings from disk to runtime...
     0.004s [ DBG load_settings       ] Try to read configfile.
     0.004s [ DBG load_settings       ] Read configfile at /media/developer/apps/usr/palm/services/org.webosbrew.piccap.service/config.json. Contents: {"backend":"libvtcapture","address":"192.168.1.11","port":19400,"width":320,"height":240,"fps":0,"autostart":true,"nogui":false,"novideo":false}
     0.005s [ DBG load_settings       ] Loaded these values: Address: 192.168.1.11 | Port: 19400 | Width: 320 | Height: 240 | FPS: 0 | Backend: libvtcapture | NoVideo: 0 | NoGUI: 0 | Autostart: 1
     0.005s [ DBG capture_main        ] Using these values: Address: 192.168.1.11 | Port: 19400 | Width: 320 | Height: 240 | FPS: 0 | Backend: libvtcapture | NoVideo: 0 | NoGUI: 0 | Autostart: 1
     0.005s [ DBG capture_main        ] Detecting backend...
     0.005s [ DBG import_backend_library] Full library path: /media/developer/apps/usr/palm/services/org.webosbrew.piccap.service/libvtcapture_backend.so
     0.006s [ ERR import_backend_library] Failed to load backend library: /media/developer/apps/usr/palm/services/org.webosbrew.piccap.service/libvtcapture_backend.so, error: libvtcapture.so.1: cannot open shared object file: No such file or directory
     0.006s [ ERR capture_main        ] Error! detect_backend.
     0.006s [ DBG cleanup             ] Starting cleanup... isRunning: 0
     0.006s [ DBG cleanup             ] Destroying hyperion-client...
     0.006s [ DBG cleanup             ] Cleanup finished.
     0.006s [ ERR main                ] Capture main init failed!
     0.006s [ DBG main                ] Going into main loop..

And finally using Libvt I get this: 

>root@LGwebOSTV:/# /media/developer/apps/usr/palm/services/org.webosbrew.piccap.service/hyperion-webos -a 192.168.1.11 --verbos
     0.001s [INFO main                ] Starting up...
     0.001s [ DBG parse_options       ] Finished parsing arguments
     0.005s [ DBG main                ] Checking service root status...
     0.005s [ DBG check_root          ] Service is running as root!
     0.005s [ DBG main                ] Setting default settings before loading...
     0.005s [ DBG set_default         ] Setting default settings to runtime...
     0.005s [ DBG set_default         ] Finished setting default.
     0.005s [ DBG main                ] Loading settings from disk to runtime...
     0.005s [ DBG load_settings       ] Try to read configfile.
     0.005s [ DBG load_settings       ] Read configfile at /media/developer/apps/usr/palm/services/org.webosbrew.piccap.service/config.json. Contents: {"backend":"libvt","address":"192.168.1.11","port":19400,"width":320,"height":240,"fps":0,"autostart":true,"nogui":false,"novideo":false}
     0.006s [ DBG load_settings       ] Loaded these values: Address: 192.168.1.11 | Port: 19400 | Width: 320 | Height: 240 | FPS: 0 | Backend: libvt | NoVideo: 0 | NoGUI: 0 | Autostart: 1
     0.006s [ DBG capture_main        ] Using these values: Address: 192.168.1.11 | Port: 19400 | Width: 320 | Height: 240 | FPS: 0 | Backend: libvt | NoVideo: 0 | NoGUI: 0 | Autostart: 1
     0.006s [ DBG capture_main        ] Detecting backend...
     0.006s [ DBG import_backend_library] Full library path: /media/developer/apps/usr/palm/services/org.webosbrew.piccap.service/libvt_backend.so
     0.026s [ DBG capture_main        ] Backend preinit...
     0.026s [INFO capture_preinit     ] Preinit called. Copying config..
     0.038s [INFO egl_init            ] [EGL] Display, major = 1, minor = 4
     0.044s [INFO egl_init            ] [EGL] Surface size: 320x240
     0.045s [INFO egl_init            ] [EGL] init complete
     0.045s [ DBG capture_main        ] Initiating capture...
     0.047s [INFO capture_init        ] [VT] VT_CreateVideoWindow
     0.047s [INFO capture_init        ] [VT] window_id=0
     0.047s [INFO capture_init        ] [VT] VT_AcquireVideoWindowResource
     0.047s [INFO capture_init        ] [VT] resource_id=85
     0.048s [INFO capture_init        ] [VT] VT_CreateContext
KADP_DE_SetDHDRInit : Done. 
     0.072s [ ERR capture_init        ] [VT] VT_CreateContext Failed
     0.073s [ ERR capture_main        ] Error! capture_init: -1
     0.073s [ DBG cleanup             ] Starting cleanup... isRunning: 0
     0.073s [ DBG cleanup             ] Destroying hyperion-client...
     0.073s [ DBG cleanup             ] Cleanup capture within library...
     0.074s [ DBG cleanup             ] Cleanup finished.
     0.074s [ ERR main                ] Capture main init failed!
     0.074s [ DBG main                ] Going into main loop..
^C     3.438s [INFO handle_signal       ] SIGINT called! Stopping capture if running..
     3.438s [ DBG main                ] Service main finishing..

Every time I tried with different resolutions as I saw some issue being resolved with that but it my case it didn't change anything.
Does anyone have any idea to make it work?
Thanks for your time

**Comment by tuxuser** [comment]
Can you please try the following binaries: https://github.com/webosbrew/hyperion-webos/actions/runs/2334937457

Overwrite all the existing libs/executables inside `/media/developer/apps/usr/palm/services/org.webosbrew.piccap.service/`

```
# Make it executable
chmod +x /media/developer/apps/usr/palm/services/org.webosbrew.piccap.service/hyperion-webos
# Delete autostart file, if it exists
rm -rf /var/lib/webosbrew/init.d/piccapautostart
# REBOOT to ensure a fresh state (sometimes when hyperion-webos was started before, it leaves in an unclean state
reboot
```

Test this build

```
cd  /media/developer/apps/usr/palm/services/org.webosbrew.piccap.service/
# DILE_VT
./hyperion-webos -a 192.168.1.11 -b libdile_vt -x 320 -y 240 -f 30 -v
# LIVTCAPTURE
./hyperion-webos -a 192.168.1.11 -b libvtcapture -x 320 -y 240 -f 30 -v
```

**Comment by DrPollio** [comment]
Hi thanks tuxuser for your answer :) 
this is what I get ( still get errors but the capture seems to be working)
>0.001s [INFO main                ] Starting up...
     0.001s [INFO main                ] Running via CLI
     0.001s [INFO service_init        ] Autodetecting UI backend...
     0.005s [ DBG unicapture_init_backend] libgm_backend.so: loading...
     0.005s [ DBG unicapture_init_backend] libgm_backend.so: loaded, initializing...
[001070.674349:hyperion-webos->hyperion-webos] <warning> GM_TEMPLATE_HASH_Insert : node already found..ptr = 0x5d4c0 
[001070.674460:hyperion-webos->hyperion-webos] <warning> GM_TEMPLATE_HASH_Insert : node already found..ptr = 0x5d8f0
[001070.674505:hyperion-webos->hyperion-webos] <warning> GM_TEMPLATE_HASH_Insert : node already found..ptr = 0x5ede0
[001070.674547:hyperion-webos->hyperion-webos] <warning> GM_TEMPLATE_HASH_Insert : node already found..ptr = 0x5f210
[001070.674596:hyperion-webos->hyperion-webos] <warning> GM_TEMPLATE_HASH_Insert : node already found..ptr = 0x5e580
[001070.674638:hyperion-webos->hyperion-webos] <warning> GM_TEMPLATE_HASH_Insert : node already found..ptr = 0x5e9b0
[001070.674692:hyperion-webos->hyperion-webos] <warning> GM_TEMPLATE_HASH_Insert : node already found..ptr = 0x5fea0
[001070.674734:hyperion-webos->hyperion-webos] <warning> GM_TEMPLATE_HASH_Insert : node already found..ptr = 0x602d0
[001070.674776:hyperion-webos->hyperion-webos] <warning> GM_TEMPLATE_HASH_Insert : node already found..ptr = 0x5fea0
[001070.674815:hyperion-webos->hyperion-webos] <warning> GM_TEMPLATE_HASH_Insert : node already found..ptr = 0x602d0
[001070.674856:hyperion-webos->hyperion-webos] <warning> GM_TEMPLATE_HASH_Insert : node already found..ptr = 0x5d4c0
[001070.674898:hyperion-webos->hyperion-webos] <warning> GM_TEMPLATE_HASH_Insert : node already found..ptr = 0x5d8f0
[001070.674947:hyperion-webos->hyperion-webos] <warning> GM_TEMPLATE_HASH_Insert : node already found..ptr = 0x60700
[001070.674988:hyperion-webos->hyperion-webos] <warning> GM_TEMPLATE_HASH_Insert : node already found..ptr = 0x60b30
[001070.675028:hyperion-webos->hyperion-webos] <warning> GM_TEMPLATE_HASH_Insert : node already found..ptr = 0x5ede0
[001070.675068:hyperion-webos->hyperion-webos] <warning> GM_TEMPLATE_HASH_Insert : node already found..ptr = 0x5f210
[001070.675108:hyperion-webos->hyperion-webos] <warning> GM_TEMPLATE_HASH_Insert : node already found..ptr = 0x60700
[001070.675148:hyperion-webos->hyperion-webos] <warning> GM_TEMPLATE_HASH_Insert : node already found..ptr = 0x60b30 
[001070.675189:hyperion-webos->hyperion-webos] <warning> GM_TEMPLATE_HASH_Insert : node already found..ptr = 0x60700
[001070.675229:hyperion-webos->hyperion-webos] <warning> GM_TEMPLATE_HASH_Insert : node already found..ptr = 0x60b30 
[001070.675267:hyperion-webos->hyperion-webos] [_GM_UseGFXHWDirectly][905] _GM_UseGFXHWDirectly OK  
     0.017s [ DBG unicapture_init_backend] libgm_backend.so: success
     0.017s [ DBG unicapture_try_backends] try_backends: libgm_backend.so succeeded
     0.018s [ DBG unicapture_init_backend] libdile_vt_backend.so: loading...
     0.018s [ DBG unicapture_init_backend] libdile_vt_backend.so: loaded, initializing...
     0.018s [INFO capture_init        ] Capture start called.
KADP_DE_SetDHDRInit : Done. 
     0.081s [ DBG capture_init        ] Got DILE_VT context!
     0.081s [ DBG capture_init        ] supportScaleUp: 1; (1920x1080)
     0.081s [ DBG capture_init        ] supportScaleDown: 1; (320x240)
     0.081s [ DBG capture_init        ] maxResolution: 1920x1080
     0.081s [ DBG capture_init        ] input deinterlace: 0; display deinterlace: 1
     0.081s [WARN capture_init        ] [DILE_VT] DISPLAY dump location failed, attempting SCALER...
     0.081s [ ERR capture_init        ] [DILE_VT] SetVideoFrameOutputDeviceDumpLocation failed!
     0.082s [ ERR unicapture_init_backend] libdile_vt_backend.so: init failure, code: -2
     0.087s [ DBG unicapture_run      ] Attempting UI capture init...
     0.087s [ DBG connection_loop     ] Starting connection loop
     0.087s [ DBG main                ] Going into main loop..
     0.087s [INFO unicapture_vsync_handler] vsync thread starting...
     0.088s [INFO unicapture_run      ] UI capture started
     0.088s [INFO connection_loop     ] Connecting hyperion-client..
     0.089s [INFO connection_loop     ] hyperion-client connected!
     0.090s [INFO power_callback      ] Power status callback message: { "subscribed": true, "returnValue": true, "state": "Active" }
     6.068s [ DBG unicapture_run      ] Framerate: 10.030375 FPS; timings - wait: 31427us, acquire: 3661us, convert: 55412us, process; 632us, send: 8447us, release: 2us
     6.069s [ DBG unicapture_run      ]         UI: pixfmt: 11; 320x240
     6.069s [ DBG unicapture_run      ]      VIDEO: pixfmt: 0; 0x0
     6.069s [ DBG unicapture_run      ] CONV    UI: pixfmt: 12; 320x240
     6.069s [ DBG unicapture_run      ] CONV VIDEO: pixfmt: 0; 0x0
    12.081s [ DBG unicapture_run      ] Framerate: 9.979401 FPS; timings - wait: 32476us, acquire: 3662us, convert: 55437us, process; 637us, send: 8291us, release: 2us

but I don't get anything on my Hyperion :( do I need to configure something more than activate de flat buffer in the network services area?

**Comment by tuxuser** [comment]
Unfortunately, it did not work :(

```
0.081s [ ERR capture_init ] [DILE_VT] SetVideoFrameOutputDeviceDumpLocation failed!
0.082s [ ERR unicapture_init_backend] libdile_vt_backend.so: init failure, code: -2
```

I will prepare a little testbuild for you in a few

**Comment by DrPollio** [comment]
thanks you, just saying I capture the UI of the web os not the all screen

**Comment by DrPollio** [comment]
Do I need to up or downgrade my webos and root it again? could this work?

**Comment by tuxuser** [comment]
No, that shouldn't be needed in most cases. Let's try the non-invasive way first.

**Comment by tuxuser** [comment]
awesome :) No worries about libvtcapture, that error is expected.
