### ISSUE TITLE
Piccap deactivates after screensaver comes on

### ISSUE THREAD

**Issue by rmp63526** [webosbrew/hyperion-webos#88]
Hi, as soon as the screensaver turns on, piccap deactivates itself and won't turn on automatically again. 
I also noticed when i turn on the TV by pushing the netflix or amazon prime button, piccap also not start.

My Details:
LG OLED65B87LC 
WebOs 4.4.0-9
Piccap 0.2.3
Hyperion.NG 0.1.7

Discord chat history:

tlp63526
Hi, any idea why Piccap stop working after my screen saver turns on? Also if i turn on the TV by pressing the Netflix button on my remote, Piccap don't start automatically.

TBSniller
some people mentioned that the screensaver also hooks at our power state check and just disables the capture

**Comment by TBSniller** [comment]
Can yo please checkout latest release? PicCap is updated to 0.4.1 by now and some screensaver bugs were fixed.

**Comment by rmp63526** [comment]
Big thanks to you mate.
Works now… and it even works now when you're in the menu.
